// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function unwrapUnsafely(v) {
  if (v !== undefined) {
    return Caml_option.valFromOption(v);
  }
  throw {
        RE_EXN_ID: "Invalid_argument",
        _1: "Passed `None` to unwrapUnsafely",
        Error: new Error()
      };
}

var app = unwrapUnsafely(Caml_option.nullable_to_opt(document.getElementById("app")));

function appendTextTo(el, classNameOpt, text) {
  var className = classNameOpt !== undefined ? classNameOpt : "";
  var textNode = document.createElement("p");
  textNode.innerText = text;
  textNode.className = className;
  el.appendChild(textNode);
  
}

function appendTextToApp(param, param$1) {
  return appendTextTo(app, param, param$1);
}

function isFizz(x) {
  if (x % 3 === 0) {
    return /* Fizz */0;
  } else {
    return /* None */1;
  }
}

function isBuzz(x) {
  if (x % 5 === 0) {
    return /* Buzz */0;
  } else {
    return /* None */1;
  }
}

function get(x) {
  var res_0 = isFizz(x);
  var res_1 = isBuzz(x);
  if (res_0) {
    if (res_1) {
      return String(x);
    } else {
      return "Buzz";
    }
  } else if (res_1) {
    return "Fizz";
  } else {
    return "FizzBuzz";
  }
}

var FizzBuzz = {
  isFizz: isFizz,
  isBuzz: isBuzz,
  get: get
};

function yesOrNo(a) {
  switch (a) {
    case "n" :
    case "no" :
        return /* No */1;
    case "y" :
    case "ya" :
    case "yea" :
    case "yeah" :
    case "yes" :
        return /* Yes */0;
    default:
      return /* No */1;
  }
}

var answer;

try {
  answer = yesOrNo($$String.lowercase_ascii(window.prompt("Do you want to guess the FizzBuzz?")));
}
catch (exn){
  answer = /* No */1;
}

var state = answer ? /* NoGuess */1 : /* Guess */0;

var $$continue = {
  contents: true
};

function guessingGame(x) {
  var guess = window.prompt("What is the result of FizzBuzz " + String(x));
  var res = get(x);
  var isCorrect = guess === res;
  if (isCorrect) {
    window.alert("Correct!");
    return appendTextTo(app, res, res);
  } else {
    window.alert("Incorrect!");
    $$continue.contents = false;
    return ;
  }
}

for(var x = 1; x <= 100; ++x){
  var match = $$continue.contents;
  if (state) {
    var res = get(x);
    appendTextTo(app, res, res);
  } else if (match) {
    guessingGame(x);
  }
  
}

exports.unwrapUnsafely = unwrapUnsafely;
exports.app = app;
exports.appendTextTo = appendTextTo;
exports.appendTextToApp = appendTextToApp;
exports.FizzBuzz = FizzBuzz;
exports.yesOrNo = yesOrNo;
exports.answer = answer;
exports.state = state;
exports.$$continue = $$continue;
exports.guessingGame = guessingGame;
/* app Not a pure module */
